### ISSUE TITLE
Estado del Proyecto/Libro

### ISSUE THREAD

**Issue by StringManolo** [StringManolo/hackingTermux101#18]
### Nuevos Capítulos
Aunque lleve casi un año sin publicar cambios, he estado trabajando en nuevos capítulos. Antes de publicarlos reviso que los códigos funcionen y que la información es correcta.  (Quizás en los próximos meses me involucre mas en el proyecto)
  
Este issue es solo para recordarles que el proyecto sigue en marcha. Pero es un proyecto difícil y he recibido hasta el momento 0 apoyo.  
  
### Apoyar El Proyecto
Si tiene las condiciones económicas recuerde que puede apoyar el proyecto con transferencia bancaria, github sponsors o XMR:
### Transferencia Bancaria
```
ES59 2080 5029 1630 0011 2266
```

### Github Sponsor
[![Sponsor](https://raw.githubusercontent.com/StringManolo/share/master/images/sponsor_card.jpg)](https://github.com/sponsors/StringManolo)

### Monero (XMR)
```
428z8183vxPDnvrU7TKpjmiYjqsknqZGVHzk458KZCnRNQWcfJbEXxd1BUfyQoRX1uPssnynN7KwMh2GMeWfK7BeFp1htMA
```

Si hace algún tipo de donación al proyecto, contácteme personalmente en [telegram](https://t.me/StringManolo) o por [email](mailto:manuelvarelacaldas@gmail.com) para poder agredecerle personalmente.   

---
  
Muchas gracias por leer.

**Comment by barrabaass** [comment]
hola manolo
excelente trabajo 😎🤘

te comento que al dar click en los link del indice, salta al titulo

y pues estoy en la parte de read y no pude con el ejercicio de la edad 😅😁
por lo demas te agradezco y te felicito, pronto pondré mi granito de arena aparte de compartir en las redes 🫡🧙🏼‍♂️

**Comment by StringManolo** [comment]
> hola manolo excelente trabajo 😎🤘
> 
> te comento que al dar click en los link del indice, salta al titulo
> 
> y pues estoy en la parte de read y no pude con el ejercicio de la edad 😅😁 por lo demas te agradezco y te felicito, pronto pondré mi granito de arena aparte de compartir en las redes 🫡🧙🏼‍♂️

Muchas Gracias!

En qué navegador y sistema operativo tienes este problema de que los link te llevan al inicio? Si me puedes dar el user agent de tu navegador, puedo bajárme la misma versión y comprobarlo. Intenta con la versión web, que es mas probable que funcione:
https://stringmanolo.github.io/hackingTermux101/#tabla-de-contenidos

Aquí un pequeño video que muestra el comportamiento esperado. 

https://github.com/user-attachments/assets/bb48add2-b700-4776-907d-a41b84254260

El código de la edad hace algo si la edad es mayor de 17. Te lo explico expresión a expresión:
```bash
1. read -p "Introduce tu edad y pulsa enter: " edad
2. if 
3. [ "$edad" -gt 17 ]; 
4. then
5. echo "Eres mayor de edad"
6. fi
```

1. Pide la edad por consola y guarda el resultado en una variable nueva llamada $edad
2. Inicia un condicional if
3. La expresión que queremos, en este caso es [ edad -MayorQue 17 ];
4. Then indica el fin de la condicion 
5. Esta linea es lo que queremos hacer si se cumple la condición. Es decir, si la edad es mayor de 17, le decimos al usuario que un adulto.
6. Finaliza el condicional if

El equivalente si bash aceptase español a este código:
```bash
Lee   -muestra "Introduce tu edad y pulsa enter: "  variableEnLaQueSeGuardaLaEdadIntroducida
si $variableEnLaQueSeGuardaLaEdadIntroducida -mayorQue 17; entonces
  imprimeEnConsola "Eres mayor de edad"
fin
```

Muchas gracias por leer.

**Comment by barrabaass** [comment]
gracias Manolo 😎🤘
ya ví el video y pude resolver el ejercicio

Muchas gracias por compartir una herramienta tan buena con todos 🧙🏼‍♂️

Si tengo otro problema te escribiré 🫡
