### ISSUE TITLE
¿por qué sólo está hasta el capítulo 25?

### ISSUE THREAD

**Issue by DagonJ** [StringManolo/hackingTermux101#7]
No está completo en la página,y desde el capítulo 26 no hay nada

**Comment by StringManolo** [comment]
Es porque está en construcción. Escribo un rato cuando me apetece. Cada cierto tiempo veras un capítulo nuevo. Si miras en los commits ves la frecuencia con la que suelo añadir nuevos capítulos. 

Gracias por leer.
